version: '3.9'

services:
  client:
    image: abulhuman/omp-client
    ports:
      - ${PORT:-3000}:3000
    restart: always
    volumes:
      - yarn:/client/.yarn
      - nuxt:/client/.nuxt
volumes:
  yarn:
  nuxt: